# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform:android do
  desc "build a version apk"
  lane :test do
    gradle(task: "clean")

    gradle(
      task: 'assemble',
      build_type: 'Debug')

    firebase_app_distribution(
      app: "app_id",
      firebase_cli_token: "token_firebase"
  )

  end
end
