# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform:android do
  desc "build a version apk"
  lane :test do
    gradle(task: "clean")

    gradle(
      task: 'assemble',
      build_type: 'Release')

    firebase_app_distribution(
      app: "1:49986261071:android:7d69196e510744fd13da3a",
      apk_path: "./app/build/outputs/apk/debug/app-debug.apk",
      firebase_cli_token: "1//0h5B86DF8rV8lCgYIARAAGBESNwF-L9IrRFmWwTbTCJGUvZ3Ipigrr9j9oP58126JI47QEq0K-2FT7wXGGZqq7AMp4EGx_ZVY-cw",
      debug: true)
  end
end
